import json
import os
import shutil
import tempfile
import unittest

from decontamlib.main import (
    human_filter_main, get_config,
)


data_dir = os.path.join(os.path.abspath(os.path.dirname(__file__)), "data")


class ConfigTests(unittest.TestCase):
    def setUp(self):
        self.temp_home_dir = tempfile.mkdtemp()
        self._old_home_dir = os.environ['HOME']
        os.environ['HOME'] = self.temp_home_dir

    def tearDown(self):
        shutil.rmtree(self.temp_home_dir)
        os.environ['HOME'] = self._old_home_dir

    def test_default_config_locataion(self):
        """Config file in user home dir should be read and used"""
        with open(os.path.join(self.temp_home_dir, ".decontam_human.json"), "w") as f:
            f.write('{"method": "SOMECRAZYVALUE"}')
        config = get_config(None, "human")
        self.assertEqual(config["method"], u"SOMECRAZYVALUE")




class HumanFilterMainTests(unittest.TestCase):
    def setUp(self):
        self.fwd_fp = os.path.join(data_dir, "B5_short_R1.fastq")
        self.rev_fp = os.path.join(data_dir, "B5_short_R2.fastq")
        self.temp_dir = tempfile.mkdtemp()
        self.output_dir = os.path.join(self.temp_dir, "output")
        self.summary_fp = os.path.join(self.temp_dir, "summary.json")
        self.org = "human"
        self.args = [
            "--forward-reads", self.fwd_fp,
            "--reverse-reads", self.rev_fp,
            "--output-dir", self.output_dir,
            "--summary-file", self.summary_fp,
            "--organism", self.org,
            ]
        self.output_fps = {
            "nonhuman": ("B5_short_R1.fastq", "B5_short_R2.fastq"),
            "human": ("B5_short_R1_human.fastq", "B5_short_R2_human.fastq"),
            }
        for k, (v1, v2) in self.output_fps.items():
            self.output_fps[k] = (
                os.path.join(self.output_dir, v1),
                os.path.join(self.output_dir, v2),
                )

    def tearDown(self):
        shutil.rmtree(self.temp_dir)

    def test_with_sam_file(self):
        sam_file = tempfile.NamedTemporaryFile(suffix=".sam")
        sam_file.write(b5_sam.encode())
        sam_file.seek(0)
        self.args.extend(["--sam-file", sam_file.name])

        # Set executable for BWA to "false"
        # This program always returns non-zero exit status
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config = {"method": "bwa", "bwa_fp": "false"}
        config_file.write(json.dumps(config).encode())
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])
        

        human_filter_main(self.args)
        for fp in self.output_fps["human"]:
            self.assertTrue(os.path.exists(fp))

        for fp in self.output_fps["nonhuman"]:
            self.assertTrue(os.path.exists(fp))


    def test_keep_sam_file(self):
        index_fp = os.path.join(data_dir, "fakehuman")
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config_file.write(json.dumps({"method": "bwa", "index": index_fp}).encode())
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])

        self.args.extend(["--keep-sam-file"])
        human_filter_main(self.args)
        sam_fp = os.path.join(self.output_dir, "B5_short_R1.sam")
        self.assertTrue(os.path.exists(sam_fp))


    def test_all_human(self):
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config_file.write(json.dumps({"method": "all_human"}).encode())
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])

        human_filter_main(self.args)

        with open(self.summary_fp) as f:
            obs_summary = json.load(f)
        self.assertEqual(obs_summary["data"], {"true": 10})

        for fp in self.output_fps["nonhuman"]:
            self.assertFalse(os.path.exists(fp))

        for fp in self.output_fps["human"]:
            with open(fp) as f:
                num_lines = len(list(f))
            self.assertEqual(num_lines, 10 * 4)


    def test_no_human(self):
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config_file.write(str.encode(json.dumps({"method": "no_human"})))
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])

        human_filter_main(self.args)

        with open(self.summary_fp) as f:
            obs_summary = json.load(f)
        self.assertEqual(obs_summary["data"], {"false": 10})

        for fp in self.output_fps["nonhuman"]:
            with open(fp) as f:
                num_lines = len(list(f))
            self.assertEqual(num_lines, 10 * 4)

        for fp in self.output_fps["human"]:
            self.assertFalse(os.path.exists(fp))


    def test_bowtie(self):
        index_fp = os.path.join(data_dir, "fakehuman")
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config_file.write(json.dumps({"method": "bowtie2", "index": index_fp}).encode())
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])

        human_filter_main(self.args)

        for fp in self.output_fps["human"]:
            self.assertTrue(os.path.exists(fp))

        for fp in self.output_fps["nonhuman"]:
            self.assertTrue(os.path.exists(fp))


    def test_bwa(self):
        index_fp = os.path.join(data_dir, "fakehuman")
        config_file = tempfile.NamedTemporaryFile(suffix=".json")
        config_file.write(json.dumps({"method": "bwa", "index": index_fp}).encode())
        config_file.seek(0)
        self.args.extend(["--config-file", config_file.name])

        human_filter_main(self.args)

        for fp in self.output_fps["human"]:
            self.assertTrue(os.path.exists(fp))

        for fp in self.output_fps["nonhuman"]:
            self.assertTrue(os.path.exists(fp))


b5_r1_nonhuman = """\
@M03249:9:000000000-ABY6B:1:1105:5122:20594 1:N:0:7
ATCTCGAACAGAGCACAAACGTAGATTATGAAACCTATCTCAATATTCAAAAAGAAAAGGACAAACTAAAACAAAAGTGGCGTGAGCCAAAAACATGACGCGCACAGCGCTAAAAAGGAATGGATTTAGCCGAGTTCCGCTTGCGCTACACACGGCAGGGCGCTAAAGCGCCATTCAAACCAAAAAACAGTTGACGTGCGGTAAAATACATGGTACAATTAGCAATAGAAAGCGAGGGAGAAAATGATTAA
+
ABCCBFFFFBFFGGGGGGGGGGHHGHHHHHHHHGHHHHHHHHHHHHHHHHHHHGGHHHHGHHHHHHHHHHHHHHHHHFGHGGGGGGHHHHHHHGHHHHGGGGGCGGHHGGGGGHHHGFHHHGHGHHHGHGHGGFFGHHGGGGGHGGGGGHHHGFGGGGGGGFGGCGGFCDCGDEFFBFGGGEEGGGFFFFBFFFFF.DEBF.AEFFEFFFFFFBBFFFFFFEFFFFFFFFFFFFFADFAFDFFFFFEFFFF
@M03249:9:000000000-ABY6B:1:1111:22567:6777 1:N:0:7
GTTGAAAGTGTTGAAAACTCGTTTTTTTAACGCTTCTACGTTTATTTATTGCCTTTTTGCTTGTTGAAAACTTTGTTGAAAACTTGTTGAATTGTTGAATGTTCGTCATTATGACGAATTTCTTTGTGCAACTTGTTGTTGAAAACCTGTTGAAAGTGTTGAAAACTCAAGTTTTCCACATTCTCTATTTTTTGGATTATTGTCTCTTTGCGTGCGTGTGCACGTTTCGTGCGCGCGCGCGTATAGTGATA
+
CCCCDFFFFFFFGGGGGGGGGGGGGGGGHHHGGGGGHHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHGGGHHHHHHHHHHHHHHHHHHHHHHHGHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGGGGGGGGGGGFFFFFFFFFFFFHFF
@M03249:9:000000000-ABY6B:1:2103:7568:11035 1:N:0:7
CGCTTGCAGCCTGTGCGCTCTGCTGGTTATATCGTTGGCTTCCAATGCTTGCAGATGCTCCTGATGTTGCGCTTGTTGCTCCGTTGGTCGCTGCCAGAATTGGGTTGATTCCCGCTGCGATCATGTCCTTTACGGTATCCTGATAGGCTGTTCCGCGCATTTCCTTCTGGAACGCTCGTTCTGCTGCTGCTTCCGCGCTGTTGTACTTCTTGGCGCTTGCTTGGCTTCCAGCATTCGCAAGGTTGCTCAGT
+
CCDCDDDFFFDFGGGGGGGGGGHHHHGHHHHHHGHHHHHHHHHHHHHHHHHHHGHHHHHHHHHGHHHHHHGGGGGHHHHHHHGHHGHGHGGGGGHHHHHHHHHHFGGHHHHHHGGGGGGGHGGHHHHHHHHHHGGHHGHHGHHHHHHHHHHHHHGGGGGGGHHHHHHHHHHHHGGGGGGGHGHHHHHGHHHGHGGGGGGGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFHFFDFFFFFFFFFFF
@M03249:9:000000000-ABY6B:1:2107:20182:17201 1:N:0:7
ATGCTGTTGGCGGCTTCGGTCGCCCTCTTGCCTATCCAGCTGTCCCGGTACAGCTCACCCGATAACGACACACGGTTTACGAGAATATGCAGGTGTGCCTGGTTCTTCCTGGTTTCCGTTCCTGAATGCTTCACTACCACATACTGGTGGTTCTTCAATCCCATGCGCTCCAGGAAGTCGTCTGCAAGCCTTTCCCAGTCATTCGGCCTCATTGTTTCGCTTTCCTCTATGCTGGGACTTACCTCAAAGCG
+
CCDDDFFFFDFDGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHGGGGGHGGGGGHGGGGGGHHGGGGGHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHGGGHHHHHHHHHHHHHHGGGGGHHHHHHGGGGGGGHHGGGGGGGHGGGGGGGHHHHGGGFFFFFFFHFFFFFFFFFHHHFFFFHFFFFFFFHFFHFFFFFFD
@M03249:9:000000000-ABY6B:1:1108:18605:20740 1:N:0:7
GACGTGCGATGTGTTCAGGCATCGCTTCGCTCATGTAGCCTGTTTCGGTGTCGAATTCGCCTAGCTCTACGAGCGAAATGTCTTCAATTTCGTTGGGCTTGCTCTCGTTGGCCTTCCATCGTGCCGTTCTGACTGCCTGTGCTCGGTTGTTCTGCAAGAATGGCTGTGAGTAGCCGTTGGTCAGTGCATCGTGGAATGAATAGAATTTCAGTTTCATGTTTTTCTCCTTTACTCTTTGTCTTTGTTTGCG
+
BBCCBCCCABCFGGGGGGGGGGHGGHHGGGGHGHHHHHHHHHHHHHGGFGGHGHGHHHGGGGGHHHHHHHGGGGGGGGHHHHHHHHHHHHHHGHHHGHHHGHHHHHGGGHHHHHHHHHGHGGHGHGGGHGHHHHHHHGHHHHHHGGGGGGHHHHHHHHHHHHHHHGFHHHFHHHHGEGGGDFGHFHFGHHGGGGGGGGFFGGGBFGGGGGGFGGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFF
@M03249:9:000000000-ABY6B:1:1112:11232:7195 1:N:0:7
TAACTTGTTAGCTGCATAGCTGTATTGCTGTGCCTGTTTTGCGCTTGAGGTTGCCATCTCGCTCGCTGCTTGTTCCCAGCTTTTCGCATTCTTGAATTGTTTTGCGCTGGTGGCCTGTTTTGCCAGCTGTAAGTATTTGTCTGCTAGCTCTGCCGTGTTGTTGCCGTATTCGTACATTGCGGATACGCTTGCAGCCTGTGCGCTCTGCTGGTTATAGCGTTGGCTTCCAATGCTTGCAGATGCTCCTGATG
+
CBCCDFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHHHHHHGGHGGGGGHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHHHHHHHGGGGGHHGHHHGHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHGGGHHHHHHHGHHHHGGGGGHGGGGGHHHHHHHHHHGGGGGGGGGGGGGGGHGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFB
@M03249:9:000000000-ABY6B:1:1110:19225:3769 1:N:0:7
GCACAACCGGGAAGTTTTGCATACGTGGCGCAGTACGTCAACAAAAAAGCCATAGGCACAGAAGAGAGCGTGAAATACTGGATGCAAGGCAGAGAACCAGAGTTTAGAATCATGTCAAAAGGTATAGGCGAAAAATATCTGAAAGAACACAAAGATGAAATCTTGAAAACAGATAGCATCATCTGTGCGGGAGGACGCGAGAAAAGGCCGCCACGCTATTTTGATAAGATTCTAGATAAAGATACCAGCCA
+
CCCCCFCCCCCCGGGGGGGGGGHHHHHGGGGGGGHHGHHGGHHHHHHGGHHHHHHHHHHHHHHHHHHGHGGGGGHHHHHHHHHHHHHHGHHGGHHHHHHHHHHHHHHHGHHHHHHHHGHHHGGHHHHHHGGGGGHHHHHHHHHHHHHHHHHGHHHHHHHHGGHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
@M03249:9:000000000-ABY6B:1:1114:7097:17216 1:N:0:7
GATTTCACGGTTATACACTGGCTGTTCGCCCAGTGCTGCAAGTCGCGGGTCGTAGTAGGTGAATCGCCCGCCGCGTGTCCACTTTGTTGCAAGCCCTTGTTGGTAACTGTGCTCTACTCGTACTACTGCCAGACCGATGATGTAG
+
BABCCFFFBCABGGGGGGGGGGHGHHHGGGGGHHHHHHHHHHHHGGGGGGGGGHGFHHHHHGHHHHGGGGGGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHHHGHHHHHHHHHHHHHHHGHGHHHHHHHHHHHGHGGGGHHHHHH
@M03249:9:000000000-ABY6B:1:1109:21977:10252 1:N:0:7
GGATCAGGCAACGAGATCACAACTGGCAGCGAGACCACAACCGGCAGTGTGACAGCACCACAACAGATAGGTTCAACACAAATCAGCACGCCAACGGGCATTACAACATTTGGTAACCAGAGCAGCGTAAACACCGCAAACGCACTGCAAATGATGAGCGGACTACTGAGCAACCTTGCGAATGCTGGAAGCCAAGCAAGCGCCAAGAAGTACAACAGCGCGGAAGCAGCAGCAGAACGAGCGTTCCAGAA
+
DECDDFFFFDFDGGGGGGGGGGGHHHHHGGGGGGGGHHHHGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHHGHHHHHHGHGHHHHHHHHGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGHHHHGGGGGGHGGGGGHHHHHHHHHHHHHGGGGGHHGGGGGGGGGGGGGGGGGGGHHGGGGGGFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFBDFFFFFF
"""

b5_r1_human = """\
@M03249:9:000000000-ABY6B:1:1102:15037:20408 1:N:0:7
AACGACACCAACTATTGGGCAGAAAAGACCGAATACAGCACACCGACTTGCACGATCGGAGGCAAGAGCGGTCTAGCTAATGGAAGCATCGGCGACTATTTCGGACTGCCGACCGAAATCACAAATAAAATCAAAGTGAACGCACTGCCGGCACGCGCCTATGCAATGATCTATAACGAGTGGTTCAGAGATGAAAACTTGGAAGCACCGTTAATGCTAGGA
+
CDEECDEEEEEEGGGGGGGGGGGHHHHGHHGGGGGHHHHHHHHGGGGGGHHHHGGHHGGGGGGGHGHHHGGGGGHHHHHHHHHHHHHHHHGGGGGGGGHHHHHGGGGHHHGGGGGGGGHHHHHHHHHHHHHHHHHHGHHHHHGGGGHHHGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFHFFFFFHFFFFFFFFFFFFFFFFFHHFF
"""

b5_sam = """\
@SQ	SN:Seq1	LN:258
@SQ	SN:Seq2	LN:288
@SQ	SN:Seq3	LN:444
@PG	ID:bwa	PN:bwa	VN:0.7.12-r1039	CL:bwa mem -M tests/data/fakehuman tests/data/B5_short_R1.fastq tests/data/B5_short_R2.fastq
M03249:9:000000000-ABY6B:1:1105:5122:20594	77	*	0	0	*	*	0	0	ATCTCGAACAGAGCACAAACGTAGATTATGAAACCTATCTCAATATTCAAAAAGAAAAGGACAAACTAAAACAAAAGTGGCGTGAGCCAAAAACATGACGCGCACAGCGCTAAAAAGGAATGGATTTAGCCGAGTTCCGCTTGCGCTACACACGGCAGGGCGCTAAAGCGCCATTCAAACCAAAAAACAGTTGACGTGCGGTAAAATACATGGTACAATTAGCAATAGAAAGCGAGGGAGAAAATGATTAA	ABCCBFFFFBFFGGGGGGGGGGHHGHHHHHHHHGHHHHHHHHHHHHHHHHHHHGGHHHHGHHHHHHHHHHHHHHHHHFGHGGGGGGHHHHHHHGHHHHGGGGGCGGHHGGGGGHHHGFHHHGHGHHHGHGHGGFFGHHGGGGGHGGGGGHHHGFGGGGGGGFGGCGGFCDCGDEFFBFGGGEEGGGFFFFBFFFFF.DEBF.AEFFEFFFFFFBBFFFFFFEFFFFFFFFFFFFFADFAFDFFFFFEFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1105:5122:20594	141	*	0	0	*	*	0	0	CCCTTTCTGTACTTTTTAGTGCGTGTGTCTATGTGTACCCATGCATTGTATACGATAATGCCGCATTCGTCCGGAATTATTTTATTCAGTTTGTTAGCAATTTCTTTTGCGCTCATTCCGTTTATTCGAATGTCTGCGGCCATACCGCGCATATGGTATGAGTACTTTGCACCGCCTACTTCTTTATTCCTTGTCGGTGTCCTGTATCCGCTGTTGACGATTACAGGTTTTCCGACTTGGTTTCTAAGGA	CCCCCFFFFDFFGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHGHHHHFGHHHHHGHGEHGHHEGCGGHHHGGGGGGGHHHHHHHHGHHHHHHHHHHHHHHHH4GHHHHHHGGGGGGHHHHHHHHHHHHHHGHHHHHHGGGGGHHGHGGGGGGGHHHHHHHHHHHHHHHHHGGHGCFGGHHHHHHHHHHHHHHGGHGGGGGGHHHGGGGGGGGGEFGFGGEGGFGGGFFFGGGGDDFFFFFFFFFFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1111:22567:6777	77	*	0	0	*	*	0	0	GTTGAAAGTGTTGAAAACTCGTTTTTTTAACGCTTCTACGTTTATTTATTGCCTTTTTGCTTGTTGAAAACTTTGTTGAAAACTTGTTGAATTGTTGAATGTTCGTCATTATGACGAATTTCTTTGTGCAACTTGTTGTTGAAAACCTGTTGAAAGTGTTGAAAACTCAAGTTTTCCACATTCTCTATTTTTTGGATTATTGTCTCTTTGCGTGCGTGTGCACGTTTCGTGCGCGCGCGCGTATAGTGATA	CCCCDFFFFFFFGGGGGGGGGGGGGGGGHHHGGGGGHHHGHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHGGGHHHHHHHHHHHHHHHHHHHHHHHGHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGGGGGGGGGGGFFFFFFFFFFFFHFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1111:22567:6777	141	*	0	0	*	*	0	0	GACTAACCCTTTCCGTGCAAAGCTAAGGTTTCCCCAACACAGGGGACACCAGACAAGCGGCAACCAAAACAAAATCATGTAAAGAAGAGGGGGGCCGCAATCAATTCTGCGGCCCCCCTTGCGTCGCGCCCCCCTACGCGGGAGGGCTGCCGCTGTAATAAGACAAACAGTCTATTATCACTATACGCGCGCGCGCACGAAACGTGCACACGCACGCAAAGAGACAATAATCCAAAAAATAGAGAATGTGG	BCCCAFFFCFFFGGGGGGGGGGHHHHHHHHHHHHHHGGGGHHHGGGGGHGHHHGHHHHGGGGGHHGHHHHHHHHHHHHHHHHHHHHHGHHGGGGGGGGGGGHHGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFFFFFFFFFFHHFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF=BBFFFFFFFFFFFFFF?A=FFFFFFFFB;FF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1102:15037:20408	97	Seq3	1	36	222M	=	1	222	AACGACACCAACTATTGGGCAGAAAAGACCGAATACAGCACACCGACTTGCACGATCGGAGGCAAGAGCGGTCTAGCTAATGGAAGCATCGGCGACTATTTCGGACTGCCGACCGAAATCACAAATAAAATCAAAGTGAACGCACTGCCGGCACGCGCCTATGCAATGATCTATAACGAGTGGTTCAGAGATGAAAACTTGGAAGCACCGTTAATGCTAGGA	CDEECDEEEEEEGGGGGGGGGGGHHHHGHHGGGGGHHHHHHHHGGGGGGHHHHGGHHGGGGGGGHGHHHGGGGGHHHHHHHHHHHHHHHHGGGGGGGGHHHHHGGGGHHHGGGGGGGGHHHHHHHHHHHHHHHHHHGHHHHHGGGGHHHGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFHFFHFFFFFHFFFFFFFFFFFFFFFFFHHFF	NM:i:1	MD:Z:22G199	AS:i:217	XS:i:197	XA:Z:Seq3,+223,222M,5;
M03249:9:000000000-ABY6B:1:1102:15037:20408	145	Seq3	1	36	222M	=	1	-222	AACGACACCAACTATTGGGCAGAAAAGACCGAATACAGCACACCGACTTGCACGATCGGAGGCAAGAGCGGTCTAGCTAATGGAAGCATCGGCGACTATTTCGGACTGCCGACCGAAATCACAAATAAAATCAAAGTGAACGCACTGCCGGCACGCGCCTATGCAATGATCTATAACGAGTGGTTCAGAGATGAAAACTTGGAAGCACCGTTAATGCTAGGA	DAFFFFFFFFFFFFFFFFFFGGGGGGGGGGGGGGGGGGGDFGGGGGGGGGHHGGGGGHHHHHHHHGGGGHHGHHHHHHHGHHHHHGGGGGGGGHHGHHGGGGHHHGGGGGGFGHHHHHHHHHHHHHHHHHGHHHHHHGGGGHHHGGGGGHGGGGGGHHHHHHHHHHHHHHHHHHGHGHHGHGHHHHHGHHHHHHHHHHHHGGGGGGGGGGFFFFFFFCCCBB	NM:i:1	MD:Z:22G199	AS:i:217	XS:i:197	XA:Z:Seq3,-223,222M,5;
M03249:9:000000000-ABY6B:1:2103:7568:11035	77	*	0	0	*	*	0	0	CGCTTGCAGCCTGTGCGCTCTGCTGGTTATATCGTTGGCTTCCAATGCTTGCAGATGCTCCTGATGTTGCGCTTGTTGCTCCGTTGGTCGCTGCCAGAATTGGGTTGATTCCCGCTGCGATCATGTCCTTTACGGTATCCTGATAGGCTGTTCCGCGCATTTCCTTCTGGAACGCTCGTTCTGCTGCTGCTTCCGCGCTGTTGTACTTCTTGGCGCTTGCTTGGCTTCCAGCATTCGCAAGGTTGCTCAGT	CCDCDDDFFFDFGGGGGGGGGGHHHHGHHHHHHGHHHHHHHHHHHHHHHHHHHGHHHHHHHHHGHHHHHHGGGGGHHHHHHHGHHGHGHGGGGGHHHHHHHHHHFGGHHHHHHGGGGGGGHGGHHHHHHHHHHGGHHGHHGHHHHHHHHHHHHHGGGGGGGHHHHHHHHHHHHGGGGGGGHGHHHHHGHHHGHGGGGGGGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFHFFDFFFFFFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:2103:7568:11035	141	*	0	0	*	*	0	0	CCTATTAACAGGCATCATAACGAGCAGTAACCAGAGCAGCGCCAAAAACAGCGAAGGATCAGGCAACGAGATCACAACTGGCAGCGAGACCACAACCGGCAGTGTGACAGCACCACAACAGATAGGTTCAACACAAATCAGCACGCCAACGGGCATTACAACATTTGGTAACCAGAGCAGCGTAAACACCGCAAACGCACTGCAAATGATGAGCGGACTACTGAGCAACCTTGCGAATGCTGGAAGCCAA	CCCCCFFFFFFCGGGGGGGGGGGGGGHHHHHHHHHHHHHHGGGGGHHEGHHHGGGGGGHHHHHHHHHGGGGGHHHHHGHHHHHGGGGGGGGHHHHGGGEGGGBCFGHHHHHHHHHHHHGHHHGHFH?GFHHHHGHGHGHHHHHHGGGGGGGCDGFHHHHGHGHCBGFFCGHGFGEGGFGGGG;AGEBFFGGGGGFEDFFFFFFFFFFBFBFFFF-CCF;FEFFFFFFFFFBFFFBFFAFFFF0FFFAFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:2107:20182:17201	77	*	0	0	*	*	0	0	ATGCTGTTGGCGGCTTCGGTCGCCCTCTTGCCTATCCAGCTGTCCCGGTACAGCTCACCCGATAACGACACACGGTTTACGAGAATATGCAGGTGTGCCTGGTTCTTCCTGGTTTCCGTTCCTGAATGCTTCACTACCACATACTGGTGGTTCTTCAATCCCATGCGCTCCAGGAAGTCGTCTGCAAGCCTTTCCCAGTCATTCGGCCTCATTGTTTCGCTTTCCTCTATGCTGGGACTTACCTCAAAGCG	CCDDDFFFFDFDGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHGGGGGHGGGGGHGGGGGGHHGGGGGHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGHGGGHHHHHHHHHHHHHHGGGGGHHHHHHGGGGGGGHHGGGGGGGHGGGGGGGHHHHGGGFFFFFFFHFFFFFFFFFHHHFFFFHFFFFFFFHFFHFFFFFFD	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:2107:20182:17201	141	*	0	0	*	*	0	0	TAGCCAAGATAAGGGGTGACCTCCAAAGGCTGAACAACTACTTCGGTGGGCGCCAGTACCGGGAGGTATTCGAGGAGAACCGGGTTATAATAGACAAACTCAAAAAGCTCTTACGATGATAGCCAAAGGAAAAAGTATCTCACATGGTACTGCAGCACTGGAGTATGACCTTGCCAAGCAGATAGCCGGAAAGGATGCGGCCACCGAAGTGTGCCGGAACGAGCTTTACGGCAGTACAGGTGCCGACATG	DDCDCFFCFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGHHHHGGGGGGEFHHHHHHGGGHHHHGGGGGHHHHHHHHHHHHHHHHHHHHGGHHHHHHGGHGHHGHHHHHHHHHHHHHGHGHHHHHHHHHHHHHHHHHHHHHHHHHHGHHHHHHHHHHHHHHGGHHGHHGHGGGGGGGGGGGGGGGGGGGAAD;FFFFFFFFFFFDFAFFFFFFFFAB9FFFFFBFFFFFA@AB	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1108:18605:20740	77	*	0	0	*	*	0	0	GACGTGCGATGTGTTCAGGCATCGCTTCGCTCATGTAGCCTGTTTCGGTGTCGAATTCGCCTAGCTCTACGAGCGAAATGTCTTCAATTTCGTTGGGCTTGCTCTCGTTGGCCTTCCATCGTGCCGTTCTGACTGCCTGTGCTCGGTTGTTCTGCAAGAATGGCTGTGAGTAGCCGTTGGTCAGTGCATCGTGGAATGAATAGAATTTCAGTTTCATGTTTTTCTCCTTTACTCTTTGTCTTTGTTTGCG	BBCCBCCCABCFGGGGGGGGGGHGGHHGGGGHGHHHHHHHHHHHHHGGFGGHGHGHHHGGGGGHHHHHHHGGGGGGGGHHHHHHHHHHHHHHGHHHGHHHGHHHHHGGGHHHHHHHHHGHGGHGHGGGHGHHHHHHHGHHHHHHGGGGGGHHHHHHHHHHHHHHHGFHHHFHHHHGEGGGDFGHFHFGHHGGGGGGGGFFGGGBFGGGGGGFGGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1108:18605:20740	141	*	0	0	*	*	0	0	GTTTTATAAACGACATCGAAATGGAACTGATCAGAAAGGAGTATAACGATGGCACATAGAAGCGGAGCAGGCAAAGGCGACCAGAAACGCTTTACACAGACTGCAAAGCGGGTGAAAAACATCAATGTGCGGCCGAAGGTATCGCGAGGCGGTATCCGGCTGTAAGCGACACAAACCAAAGAAAAGAGGTGACTTAATGGCACTGATCAAGATCAAAGACGTCAAGGAAGCAATTGCGCTGATGATGAAAA	AABBBFFFFFFBGFGGGGGGGGHHHHHHHHHHHHGHHHHHGHHHHHGGGGFFHHHHHHFHHHHGGGGGHHHGHHHHHGGGGGGHHHHHGGGGGHHHHHHHGHGHHHGHHGGGBDHHHHHGHHHHHHGHHHGGGGGGGGGGGGHGGGGGGGGG?EGFGGGGGGGGE9FFFFFFFFFFF?FEFB?FFFFFF/:/FFFFFFFFFFFFFFFFFFFFFFBFFFFFDFFFFFFFF..FFFFFFFFFFBFFFFFFFEF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1112:11232:7195	77	*	0	0	*	*	0	0	TAACTTGTTAGCTGCATAGCTGTATTGCTGTGCCTGTTTTGCGCTTGAGGTTGCCATCTCGCTCGCTGCTTGTTCCCAGCTTTTCGCATTCTTGAATTGTTTTGCGCTGGTGGCCTGTTTTGCCAGCTGTAAGTATTTGTCTGCTAGCTCTGCCGTGTTGTTGCCGTATTCGTACATTGCGGATACGCTTGCAGCCTGTGCGCTCTGCTGGTTATAGCGTTGGCTTCCAATGCTTGCAGATGCTCCTGATG	CBCCDFFFFFFFGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHHHHHHGGHGGGGGHHHHHHHHHHHHHHHHGGGGGHHHHHHHHHHHHHHHGGGGGHHGHHHGHHHHHHHHHGHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGHHHHHHHHGGGHHHHHHHGHHHHGGGGGHGGGGGHHHHHHHHHHGGGGGGGGGGGGGGGHGGGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFB	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1112:11232:7195	141	*	0	0	*	*	0	0	TTCCAGAAGGAAATGCGCGGAACAGCCTATCAGGATACCGTAAAGGACATGATCGCAGCGGGAATCAACCCAATTCTGGCAGCGACCAACGGAGCAACAAGCGCAACATCAGGAGCATCTGCAAGCATTGGAAGCCAACGCTATAACCAGCAGAGCGCACAGGCTGCAAGCGTATCCGCAATGTACGAATACGGCAACAACACGGCAGAGCTAGCAGACAAATACTTACAGCTGGCAAAACAGGCCACCA	CCCCCFFFFFFFGGGGGGGGGGGHHHHHHHHHHHHHHHHGGHGHHHHHHHHHHHGGGGGGGGGGHHHHHHGGHHHGHHHHHGGGGGGGHGGGGGGHHHHHHHGGGGGHHHHHHHGHHHHHHHHHHHHHHHHHHFHHHGGGGGGGGHHHHHHHHHHHGGGGGGGGGGGGGGGGGGFGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFBFFFBFFFFFFFFFFFFEFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1110:19225:3769	77	*	0	0	*	*	0	0	GCACAACCGGGAAGTTTTGCATACGTGGCGCAGTACGTCAACAAAAAAGCCATAGGCACAGAAGAGAGCGTGAAATACTGGATGCAAGGCAGAGAACCAGAGTTTAGAATCATGTCAAAAGGTATAGGCGAAAAATATCTGAAAGAACACAAAGATGAAATCTTGAAAACAGATAGCATCATCTGTGCGGGAGGACGCGAGAAAAGGCCGCCACGCTATTTTGATAAGATTCTAGATAAAGATACCAGCCA	CCCCCFCCCCCCGGGGGGGGGGHHHHHGGGGGGGHHGHHGGHHHHHHGGHHHHHHHHHHHHHHHHHHGHGGGGGHHHHHHHHHHHHHHGHHGGHHHHHHHHHHHHHHHGHHHHHHHHGHHHGGHHHHHHGGGGGHHHHHHHHHHHHHHHHHGHHHHHHHHGGHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1110:19225:3769	141	*	0	0	*	*	0	0	AATACGACTTGTGACCCGTCTTTGCAAGCGAATTCCTTTACTTTGAAGTGTTGCCCTACTTTTTCGTTTGCGTCGGTGTCCATGATGTAGCTTTTAATCATTTTCTCCCTCGCTTTCTATTGCTAATTGTACCATGTATTTTACCGCACGTCAACTGTTTTTTGGTTTGAATGGCGCTTTAGCGCCCTGCCGTGTGTAGCGCAAGCGGAACTCGGCTAAATCCATTCCTTTTTAGCGCTGTGCGCGTCATG	3ABBBBABBBFFGGGGGGGGGGGHHHHHHGFEGHHHHHHHHHHHHHFHHHHHHHGHHHHHHHHHHGHHGGHGGGGGGGGHHGHHHHHHHGHHHHHHHHHDHHHHHHHHHHHGGGHGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGHHGGHHHHHHHGGGGHHHGGHHFHHGGGGGHGHCGFGGHHHGFGGGGEFGAGGG?EFF?DFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFFFFFFFCFFFB	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1114:7097:17216	77	*	0	0	*	*	0	0	GATTTCACGGTTATACACTGGCTGTTCGCCCAGTGCTGCAAGTCGCGGGTCGTAGTAGGTGAATCGCCCGCCGCGTGTCCACTTTGTTGCAAGCCCTTGTTGGTAACTGTGCTCTACTCGTACTACTGCCAGACCGATGATGTAG	BABCCFFFBCABGGGGGGGGGGHGHHHGGGGGHHHHHHHHHHHHGGGGGGGGGHGFHHHHHGHHHHGGGGGGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHHHGHHHHHHHHHHHHHHHGHGHHHHHHHHHHHGHGGGGHHHHHH	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1114:7097:17216	141	*	0	0	*	*	0	0	CGGCTACATCATCGGTCTGGCAGTAGTACGAGTAGAGCACAGTTACCAACAAGGGCTTGCAACAAAGTGGACACGCGGCGGGCGATTCACCTACTACGACCCGCGACTTGCAGCACTGGGCGAACAGCCAGTGTATAACCGTGAAATC	ABABABFFFFFFGGGGGGGGGGGHFHHHHGGGGHHHHHHHHHHHHHHHHGGHHGGGGHGHHGHHHHHHHHHHHHGGGGGGGGGGGFHHGHHHHHHHHGGGGGGGGGGGGHHHGHHGHHHHHGGGGGGGGGGFFFGGGGGGGFGGGEGG	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1109:21977:10252	77	*	0	0	*	*	0	0	GGATCAGGCAACGAGATCACAACTGGCAGCGAGACCACAACCGGCAGTGTGACAGCACCACAACAGATAGGTTCAACACAAATCAGCACGCCAACGGGCATTACAACATTTGGTAACCAGAGCAGCGTAAACACCGCAAACGCACTGCAAATGATGAGCGGACTACTGAGCAACCTTGCGAATGCTGGAAGCCAAGCAAGCGCCAAGAAGTACAACAGCGCGGAAGCAGCAGCAGAACGAGCGTTCCAGAA	DECDDFFFFDFDGGGGGGGGGGGHHHHHGGGGGGGGHHHHGGGGGGGHHHHHHHHHHHHHHHHGHHHHHHHGHHHHHHGHGHHHHHHHHGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGHHHHGGGGGGHGGGGGHHHHHHHHHHHHHGGGGGHHGGGGGGGGGGGGGGGGGGGHHGGGGGGFFFFFFFFFFFFFFFFFBFFFFFFFFFFFFAFFFFFFFFFFFFFFFFFFFBDFFFFFF	AS:i:0	XS:i:0
M03249:9:000000000-ABY6B:1:1109:21977:10252	141	*	0	0	*	*	0	0	GGCTTCCAATGCTTGCAGATGCTCCTGATGGTGCGCTTGTTGCTCCGTTGGTCGCTGCCAGAATTGGGTTGATTCCCGCTGCGATCATGTCCTTTACGGTATCCTGATAGGCTGTTCCGCGCATTTCCTTCTGGAACGCTCGTTCTGCTGCTGCTTCCGCGCTGTTGTACTTCTTGGCGCTTGCTTGGCTTCCAGCATTCGCAAGGTTGCTCAGTAGTCCGCTCATCATTTGCAGTGCGTTTGCGGTGTTT	BBBCCFFFFFFFGGGGGGGGGGHHHHHHHHHHHHGGGGGHHHHHHHGHHGHGHGGGGGHHHFHHHHHHGGGHHHHHHGGGGGGGGGGHHHHHHHHHHGGHHGHHHHHHGHHHHHHHHHGGGGGGGHHHHHHHHHHHHGGGGGGGHGHHHHHHHHHHHHGGGGGGGGHHHHHHHHHHHGGGGGGGHHGGGGGGGGFGFFGGGGG??GGGGFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFAFFFFDFDFF	AS:i:0	XS:i:0
"""


if __name__ == "__main__":
    unittest.main()